### ISSUE TITLE
Errors Installing & Usage

### ISSUE THREAD

**Issue by amjiddader** [iGerman00/Pollyduble#1]
#2  We can not install due to pip dependencies errors. 
Still if we somehow manage to install it it does not work?

I am installing on Windows with Nvidia GPU and i tried several methods but i was not able to install due to pip deps issues.
Somehow i managed to get pass using pip-tools now i have installed.

Its giving below error and the file "OpenVoice/checkpoints_v2/converter/config.json'" actually does not exist

----

Loading libraries...
Initializing folders at C:\Users\Amjad\Videos\dub\Polydub\output
Using device: cuda
Traceback (most recent call last):
  File "C:\Users\Amjad\Videos\dub\demo.py", line 263, in <module>
    main()
  File "C:\Users\Amjad\Videos\dub\demo.py", line 245, in main
    tone_color_converter = init_tone_color_converter()
  File "C:\Users\Amjad\Videos\dub\demo.py", line 62, in init_tone_color_converter
    tone_color_converter = ToneColorConverter(f'{config["CKPT_CONVERTER"]}/config.json', device=device)
  File "c:\users\amjad\videos\dub\src\myshell-openvoice\openvoice\api.py", line 103, in __init__
    super().__init__(*args, **kwargs)
  File "c:\users\amjad\videos\dub\src\myshell-openvoice\openvoice\api.py", line 21, in __init__
    hps = utils.get_hparams_from_file(config_path)
  File "c:\users\amjad\videos\dub\src\myshell-openvoice\openvoice\utils.py", line 7, in get_hparams_from_file
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'OpenVoice/checkpoints_v2/converter/config.json'

**Comment by iGerman00** [comment]
That just shows that you haven't got the proper directory structure. You need to download the OpenVoice models - follow their instructions for the demos.

**Comment by amjiddader** [comment]
i got that, working now, thanks, 

But it has simple TTS voice, i was expecting voice clone to clone the real looking voice from audio
